name: Labeler

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  security-events: write
  pull-requests: write

jobs:

  dump-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context "GitHub"
        env:
          GITHUB_CONTEXT: {% raw %}${{ toJson(github) }}{% endraw %}
        run: echo "$GITHUB_CONTEXT"

  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5.0.0
        with:
          skip-delete: true
          github-token: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
