name: Tests

on:
  push:
  pull_request:

concurrency:
  group: {% raw %}${{ github.workflow }}-${{ github.head_ref || github.run_id }}{% endraw %}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:

  dump-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context "GitHub"
        env:
          GITHUB_CONTEXT: {% raw %}${{ toJson(github) }}{% endraw %}
        run: echo "$GITHUB_CONTEXT"

  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ '3.9', '3.10', '3.11', '3.12', '3.13' ]
    runs-on: {% raw %}${{ matrix.os }}{% endraw %}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
        uses: actions/setup-python@v5
        with:
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch pre-commit
          hatch env create
      - name: Lint and typecheck
        run: |
          hatch run lint:all
      - name: Run Tests
        run: |
          hatch test
